### GET/
GET http://localhost:4001/ HTTP/1.1

### GET /articles
GET http://localhost:4001/articles HTTP/1.1

### POST to /articles
POST http://localhost:4001/articles HTTP/1.1
Content-Type: application/json

{
    "title": "Title",
    "body": "Body"
}

### GET /articles/:id
GET http://localhost:4001/articles/4 HTTP/1.1

### PATCH to /articles/:id == update article with declared id
PATCH http://localhost:4001/articles/4 HTTP/1.1
Content-Type: application/json

{
    "title": "Patched Title",
    "body": "Patched Body"
}

### DELETE /articles/:id 
DELETE http://localhost:4001/articles/4 HTTP/1.1